### ISSUE TITLE
Symbols in XWD files have different length

### ISSUE THREAD

**Issue by MelvisR** [mattiasclaesson/T8SuitePro#7]
As the some symbols in XWD files has got a different length than the FWD files they are not shown correct. 
Example is symbol FFFuelCal.afterStartMAP (Symbolnumber 4907 in FF0C_C_FME1_73_FIEF_82z) which is length 134 but in an FD0M file it's 118.

**Comment by mattiasclaesson** [comment]
fixed by faanskit!
