### ISSUE TITLE
Move files that need write and create  permisssions to the users profiles

### ISSUE THREAD

**Issue by MelvisR** [mattiasclaesson/T8SuitePro#8]
All suites have issues when it comes to write and create permissions in the Txsuite folder in %program files%, I suggest a move of the files created to the users profile instead.

**Comment by mattiasclaesson** [comment]
Repository is no longer used, instead a xml file is create with the same name as the bin file but with extension xml.
Logging location have been changed from program files to %appdata%\MattiasC.
